export const baseStyle = {
    flex: 1,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: '60vh',
    maxHeight: '90vh',
    width: '100%',
    objectFit: 'contain',
    flexDirection: 'column',
    // padding: "20px",
    borderWidth: 2,

    color: '#bdbdbd ',
    outline: 'none',
    transition: 'border .24s ease-in-out',
    cursor: 'pointer',
    overflow: 'hidden',
    border: '10px dashed #eeeeee',
  };